## 2.2 NumPy 模块的数组对象

### 2.2.1 创建数组对象

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
print(f"arr1 shape: {arr1.shape}")

[10 20 30 40 50]
arr1 shape: (5,)


In [2]:
arr2 = np.array([10, 20, 30, 40, 50], ndmin=2)
print(arr2)
print(f"arr2 shape: {arr2.shape}")

[[10 20 30 40 50]]
arr2 shape: (1, 5)


In [3]:
arr3 = np.array([10, 20, 30, 40, 50], dtype=complex)
print(arr3)
print(f"arr3 shape: {arr3.shape}")

[10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j]
arr3 shape: (5,)


In [4]:
lists1 = [[101, 202, 303], [404, 505, 606]]
arr4 = np.array(lists1)
print(f"arr4 type: {type(arr4)}")
print(f"arr4 shape: {arr4.shape}")

arr4 type: <class 'numpy.ndarray'>
arr4 shape: (2, 3)


In [5]:
arr5 = np.zeros((3, 4))
print(arr5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
arr6 = np.ones((3, 4))
print(arr6)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr7 = np.eye(4)
print(arr7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr8 = np.identity(4)
print(arr8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
arr9 = np.empty((3, 4))
print(arr9)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 2.2.2 数组对象类型的说明

In [12]:
import numpy as np

arr1 = np.array([12.5, 136.7, 24.6, 35.5, 109.8])
int_arr1 = arr1.astype(int)
str_arr1 = arr1.astype(str)
print(
    f"arr1 dtype: {arr1.dtype}\nint_arr1 dtype: {int_arr1.dtype}\nstr_arr1 dtype: {str_arr1.dtype}"
)

arr1 dtype: float64
int_arr1 dtype: int64
str_arr1 dtype: <U32


### 2.2.3 随机生成数组