## 2.2 NumPy 模块的数组对象

### 2.2.1 创建数组对象

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
print(f"arr1 shape: {arr1.shape}")

[10 20 30 40 50]
arr1 shape: (5,)


In [2]:
arr2 = np.array([10, 20, 30, 40, 50], ndmin=2)
print(arr2)
print(f"arr2 shape: {arr2.shape}")

[[10 20 30 40 50]]
arr2 shape: (1, 5)


In [3]:
arr3 = np.array([10, 20, 30, 40, 50], dtype=complex)
print(arr3)
print(f"arr3 shape: {arr3.shape}")

[10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j]
arr3 shape: (5,)


In [4]:
lists1 = [[101, 202, 303], [404, 505, 606]]
arr4 = np.array(lists1)
print(f"arr4 type: {type(arr4)}")
print(f"arr4 shape: {arr4.shape}")

arr4 type: <class 'numpy.ndarray'>
arr4 shape: (2, 3)


In [5]:
arr5 = np.zeros((3, 4))
print(arr5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
arr6 = np.ones((3, 4))
print(arr6)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr7 = np.eye(4)
print(arr7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr8 = np.identity(4)
print(arr8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
arr9 = np.empty((3, 4))
print(arr9)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 2.2.2 数组对象类型的说明

In [12]:
import numpy as np

arr1 = np.array([12.5, 136.7, 24.6, 35.5, 109.8])
int_arr1 = arr1.astype(int)
str_arr1 = arr1.astype(str)
print(
    f"arr1 dtype: {arr1.dtype}\nint_arr1 dtype: {int_arr1.dtype}\nstr_arr1 dtype: {str_arr1.dtype}"
)

arr1 dtype: float64
int_arr1 dtype: int64
str_arr1 dtype: <U32


### 2.2.3 随机生成数组

In [1]:
import numpy as np

samples = np.random.normal(size=(4, 4))
print(samples)

[[-0.01359357 -0.40962299 -1.60367816 -1.04570208]
 [-1.78092467 -0.91605115  2.4291065  -1.07420118]
 [ 0.17828766  2.25509371 -1.0280496  -0.27048406]
 [-0.4080115   1.84439326 -0.86979869 -1.86786928]]


In [1]:
from random import normalvariate
import time
import numpy as np

n = 10000000
start = time.time()
samples = [normalvariate(0, 1) for i in range(n)]
times = np.random.normal(size=n)
end = time.time()
print(f"from start to end: {end - start} seconds")

from start to end: 3.583648920059204 seconds


## NumPy 模块中数组的广播

In [2]:
import numpy as np

arr1 = np.array([[10, 20, 30], [7, 8, 9]])
multi_arr = arr1 * arr1
sub_arr = arr1 - arr1
print(f"大小相等的数组实现乘法：\n{multi_arr}")
print(f"大小相等的数组实现减法：\n{sub_arr}")

大小相等的数组实现乘法：
[[100 400 900]
 [ 49  64  81]]
大小相等的数组实现减法：
[[0 0 0]
 [0 0 0]]


In [4]:
divide_arr = 100 / arr1
multi_arr = arr1 * 0.5
print(f"数组与标量值的除法运算：\n{divide_arr}")
print(f"数组与标量值的乘法运算：\n{multi_arr}")

数组与标量值的除法运算：
[[10.          5.          3.33333333]
 [14.28571429 12.5        11.11111111]]
数组与标量值的乘法运算：
[[ 5.  10.  15. ]
 [ 3.5  4.   4.5]]


### 2.3.1 数组广播的原则
列方向上取均值，即沿着 0 轴取均值，结果为 1 行 n 列。

In [6]:
import numpy as np

weathers = np.array(
    [
        [20, 21, 22, 18, 19, 21, 22],
        [18, 21, 23, 19, 18, 21, 13],
        [18, 19, 22, 21, 21, 17, 16],
        [15, 18, 20, 19, 21, 17, 18],
    ]
)
print(f"weather mean: \n{weathers.mean(0)}")
meaned = weathers - weathers.mean(0)
print(f"meaned: \n{meaned}")
print(f"meaned.mean(0): \n{meaned.mean(0)}")

weather mean: 
[17.75 19.75 21.75 19.25 19.75 19.   17.25]
meaned: 
[[ 2.25  1.25  0.25 -1.25 -0.75  2.    4.75]
 [ 0.25  1.25  1.25 -0.25 -1.75  2.   -4.25]
 [ 0.25 -0.75  0.25  1.75  1.25 -2.   -1.25]
 [-2.75 -1.75 -1.75 -0.25  1.25 -2.    0.75]]
meaned.mean(0): 
[0. 0. 0. 0. 0. 0. 0.]


行方向上取均值，即沿着 1 轴取均值，结果为 1 行 m 列，需要 reshape 成 m 行 1 列。

In [7]:
print(f"mean(1) reshaped to (4,1): \n{weathers.mean(1).reshape(4,1)}")
meaned = weathers - weathers.mean(1).reshape(4, 1)
print(f"meaned: \n{meaned}")
print(f"meaned.mean(1): \n{meaned.mean(1)}")

mean(1) reshaped to (4,1): 
[[20.42857143]
 [19.        ]
 [19.14285714]
 [18.28571429]]
meaned: 
[[-0.42857143  0.57142857  1.57142857 -2.42857143 -1.42857143  0.57142857
   1.57142857]
 [-1.          2.          4.          0.         -1.          2.
  -6.        ]
 [-1.14285714 -0.14285714  2.85714286  1.85714286  1.85714286 -2.14285714
  -3.14285714]
 [-3.28571429 -0.28571429  1.71428571  0.71428571  2.71428571 -1.28571429
  -0.28571429]]
meaned.mean(1): 
[1.52259158e-15 0.00000000e+00 5.07530526e-16 1.01506105e-15]


### 数组广播的妙用

In [9]:
import numpy as np

arr = np.ones((4, 6))
print(f"original array:\n{arr}")
arr = arr * 7
print(f"arr * 7:\n{arr}")

original array:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
arr * 7:
[[7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7.]]
